export enum AGGREGATORS {
  ONE_INCH = "one_inch",
  NITRO = "nitro",
  CHANGE_NOW = "change_now",
  OPEN_OCEAN = "open_ocean",
  SYMBIOSIS = "symbiosis",
  UNIZEN = "unizen",

  ICECREAM_SWAP = "icecream_swap",
  KYBER_SWAP = "kyber_swap",
  LIFI = "lifi",
  BUTTER_NETWORK = "butter_network",
  SQUID_ROUTER = "squid_router",
  KIMA = "kima",
  NORDSTERN = "nordstern",
  ODOS = "odos",
  RELAY = "relay",
  SUSHISWAP = "sushiswap",
  ACROSS = "across",
  NEAR_1CLICK = "near_1click",
  GAS_ZIP = "gas_zip",
  RHINO_FI = "rhino_fi",
  OKX = "okx",
  RANGO = "rango",
  DEBRIDGE = "debridge",
  XY_FINANCE = "xy_finance",
  HOUDINI = "houdini",
  UNISWAP = "uniswap",
}
